import comment__style from "../components/_Homepage/_Feedback/Comments/styles.module.css";

const comments = [
    {
      comments: "I really enjoyed the workshops, they were really cool and fun, I had the time of my life and with the certificate I got a job at Google, it changed my life.",
      translation: "Gostei muito das oficinas, elas foram muito legais e divertidas, tive o tempo da minha vida e com o certificado consegui um emprego na Google, mudou minha vida.",
      name: "Pedrinho",
      info: "Aluno de inglês",
      className: comment__style.comments,
      image: "/blueGhost.svg",
      headerStyle: comment__style.comments__header,
      nameStyle: comment__style.header__name,
      infoStyle: comment__style.header__info,
      textStyle: comment__style.comments__text,
      translationStyle: comment__style.comments__text__translation,
    },
    {
      comments: "I loved the workshops; they were amazing. Because of everything I learned, I was able to sing all the songs at Taylor Swift's concert.",
      translation: "Adorei as oficinas, foram incríveis, por conta de tudo que aprendi consegui cantar todas as músicas no show da Taylor Swift.",
      name: "Clara",
      info: "Aluna de inglês",
      className: comment__style.comments__blue,
      headerStyle: comment__style.comments__header_blue,
      nameStyle: comment__style.header__name_blue,
      infoStyle: comment__style.header__info_blue,
      textStyle: comment__style.comments__text_blue,
      translationStyle: comment__style.comments__text__translation_blue,
      image: "/ghost.svg",
    },
    {
      comments: "I was able to personally talk to my favorite idol from a K-pop group, it was an incredible experience, highly recommend.",
      translation: "Pude conversar pessoalmente com minha idol preferida de um grupo de K-pop, foi uma experiência incrível, recomendo muito.",
      name: "José",
      info: "Aluno de inglês",
      className: comment__style.comments,
      image: "/blueGhost.svg",
      headerStyle: comment__style.comments__header,
      nameStyle: comment__style.header__name,
      infoStyle: comment__style.header__info,
      textStyle: comment__style.comments__text,
      translationStyle: comment__style.comments__text__translation,
    },
    {
      comments: "I loved the workshops; they were amazing. Because of everything I learned, I was able to sing all the songs at Taylor Swift's concert.",
      translation: "Adorei as oficinas, foram incríveis, por conta de tudo que aprendi consegui cantar todas as músicas no show da Taylor Swift.",
      name: "Clara",
      info: "Aluna de inglês",
      className: comment__style.comments__blue,
      headerStyle: comment__style.comments__header_blue,
      nameStyle: comment__style.header__name_blue,
      infoStyle: comment__style.header__info_blue,
      textStyle: comment__style.comments__text_blue,
      translationStyle: comment__style.comments__text__translation_blue,
      image: "/ghost.svg",
    },
    {
      comments: "I was able to personally talk to my favorite idol from a K-pop group, it was an incredible experience, highly recommend.",
      translation: "Pude conversar pessoalmente com minha idol preferida de um grupo de K-pop, foi uma experiência incrível, recomendo muito.",
      name: "José",
      info: "Aluno de inglês",
      className: comment__style.comments,
      image: "/blueGhost.svg",
      headerStyle: comment__style.comments__header,
      nameStyle: comment__style.header__name,
      infoStyle: comment__style.header__info,
      textStyle: comment__style.comments__text,
      translationStyle: comment__style.comments__text__translation,
    },
    {
      comments: "I loved the workshops; they were amazing. Because of everything I learned, I was able to sing all the songs at Taylor Swift's concert.",
      translation: "Adorei as oficinas, foram incríveis, por conta de tudo que aprendi consegui cantar todas as músicas no show da Taylor Swift.",
      name: "Clara",
      info: "Aluna de inglês",
      className: comment__style.comments__blue,
      headerStyle: comment__style.comments__header_blue,
      nameStyle: comment__style.header__name_blue,
      infoStyle: comment__style.header__info_blue,
      textStyle: comment__style.comments__text_blue,
      translationStyle: comment__style.comments__text__translation_blue,
      image: "/ghost.svg",
    },
    {
      comments: "I was able to personally talk to my favorite idol from a K-pop group, it was an incredible experience, highly recommend.",
      translation: "Pude conversar pessoalmente com minha idol preferida de um grupo de K-pop, foi uma experiência incrível, recomendo muito.",
      name: "José",
      info: "Aluno de inglês",
      className: comment__style.comments,
      image: "/blueGhost.svg",
      headerStyle: comment__style.comments__header,
      nameStyle: comment__style.header__name,
      infoStyle: comment__style.header__info,
      textStyle: comment__style.comments__text,
      translationStyle: comment__style.comments__text__translation,
    },
    {
      comments: "I loved the workshops; they were amazing. Because of everything I learned, I was able to sing all the songs at Taylor Swift's concert.",
      translation: "Adorei as oficinas, foram incríveis, por conta de tudo que aprendi consegui cantar todas as músicas no show da Taylor Swift.",
      name: "Clara",
      info: "Aluna de inglês",
      className: comment__style.comments__blue,
      headerStyle: comment__style.comments__header_blue,
      nameStyle: comment__style.header__name_blue,
      infoStyle: comment__style.header__info_blue,
      textStyle: comment__style.comments__text_blue,
      translationStyle: comment__style.comments__text__translation_blue,
      image: "/ghost.svg",
    },
    
  ];
  
  export default comments;
  